<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Promise</title>
</head>

<body>

</body>

<script>
  const PENDING = 'pending';
  const FULFILLED = 'fulfilled';
  const REJECTED = 'rejected';

  class MyPromise {
    status = PENDING;
    // 存储 resolve 和 reject 的参数
    value = undefined;
    reason = undefined;
    // 异步情况 存储then 方法中的成功回调 和 失败回调
    successCallBack = [];
    failCallBack = [];

    constructor(executor) {
      // 在执行 执行器时 若抛出错误 需要捕获错误
      try {
        executor(this.resolve, this.reject);
      } catch (error) {
        this.reject(error.message);
      }
    }

    resolve = value => {
      if (this.status !== PENDING) return;
      // 执行resolve 更改状态
      this.status = FULFILLED;

      this.value = value;
      // 等待同步执行完后 执行异步
      while (this.successCallBack.length) this.successCallBack.shift()();
    }

    reject = reason => {
      if (this.status !== PENDING) return;
      // 执行reject 更改状态
      this.status = REJECTED;

      this.reason = reason;
      // 等待同步执行完后 执行异步
      while (this.failCallBack.length) this.failCallBack.shift()();
    }

    /*
      1. then方法传递两个回调函数 成功回调 失败回调
      2. 同步情况 判断resolve reject 方法执行后的status的状态 执行回调函数
      3. 异步情况 先存储成功回调和失败回调
      4. then方法返回一个Promise
         then方法返回的Promise 可以作为一个Promise调用
      5. then方法的链式调用
         下一个then方法的value值是上一个then方法返回的value
         value 可以是 普通值 也可以是 Promise
         判断状态 成功 则调用resolve 失败调用reject
      6. 判断上一个then方法返回的值 是普通值 还是 Promise 
         如果是普通值 直接调用resolve 
         如果是Promise 调用then方法执行返回的Promise 等待这个Promise执行完毕
          如果Promise执行成功 就走下一个then的成功
          如果Promise执行失败 就走下一个then的失败
      7. then方法的Promise 和 返回给下一个then方法的Promise是不同的
         then方法返回的Promise方法是全新的 
         判断then方法返回给下一个then方法Promise 和 then方法本身返回的Promise 是不同的
         避免then方法Promise 循环回调
      8. then方法中 捕获错误
         成功回调 错误捕获
         失败回调 错误捕获
         异步情况 错误捕获

    */

    then (successCallBack, failCallBack) {
      // then方法不传递参数 参数向下传递
      successCallBack = successCallBack ? successCallBack : value => value;
      failCallBack = failCallBack ? failCallBack : reason => { throw reason };
      const promiseReturn = new MyPromise((resolve, reject) => {
        if (this.status === FULFILLED) {
          setTimeout(() => {
            // 成功回调 错误捕获
            try {
              let x = successCallBack(this.value);
              resolvePromise(promiseReturn, x, resolve, reject);
            } catch (error) {
              reject(error);
            }
          }, 0)

        } else if (this.status === REJECTED) {
          setTimeout(() => {
            // 失败回调 成功捕获
            try {
              let x = failCallBack(this.reason);
              resolvePromise(promiseReturn, x, resolve, reject);
            } catch (error) {
              reject(error);
            }
          }, 0)
        } else {
          // 异步情况
          // resolve reject 等待执行
          // 先执行then方法 等同步代码执行完后 再执行异步代码
          // 存储successCallBack failCallBack 方法
          // 异步情况 捕获错误
          this.successCallBack.push(() => {
            setTimeout(() => {
              // 成功回调 错误捕获
              try {
                let x = successCallBack(this.value);
                resolvePromise(promiseReturn, x, resolve, reject);
              } catch (error) {
                reject(error);
              }
            }, 0)
          })
          this.failCallBack.push(() => {
            setTimeout(() => {
              // 失败回调 成功捕获
              try {
                let x = failCallBack(this.reason);
                resolvePromise(promiseReturn, x, resolve, reject);
              } catch (error) {
                reject(error);
              }
            }, 0)
          })
        }
      })
      return promiseReturn;
    }

    // 不管成功还是失败，都会走到finally中,并且finally之后，还可以继续then。并且会将值原封不动的传递给后面的then.
    finally (callback) {
      return this.then(value => {
        return MyPromise.resolve(callback()).then(() => value);
      }, reason => {
        return MyPromise.resolve(callback()).then(() => { throw reason });
      })
    }

    // 用于指定出错时的回调 是特殊的then方法 catch之后 可以继续 .then
    // then方法抛出错误 后续的then方法不会执行 直接执行catch 抛出错误
    catch (failCallBack) {
      return this.then(undefined, failCallBack);
    }

    /*
     1. promise all 是解决异步并发问题
     2. all 方法的执行顺序就是 结果的顺序
     3. all 方法也是返回的一个Promise对象
     4. all 方法中的方法状态全部是成功的 结果也是成功的 如果有一个是失败的 结果就是失败的
    */
    static all (array) {
      let result = [];
      let index = 0;

      return new MyPromise((resolve, reject) => {
        function addData (key, value) {
          result[key] = value;
          index++;
          if (index === array.length) {
            resolve(result)
          }
        }
        for (let i = 0; i < array.length; i++) {
          const current = array[i];
          // 判断all方法中是 普通值还是Promise对象
          if (current instanceof MyPromise) {
            // Promise对象
            current.then(value => addData(i, value), reason => reject(reason));
          } else {
            // 普通值
            addData(i, array[i]);
          }
        }
      })
    }

    /*
     1. Promise resolve 方法就是将给定的值转换成Promise对象
     2. resolve 返回的是一个Promise对象
     3. 若resolve 参数是一个Promise对象 直接返回
     4. 若resolve 参数是一个普通值 包装成Promise 返回
    */
    static resolve (value) {
      if (value instanceof MyPromise) return value;
      return new MyPromise(resolve => resolve(value));
    }


  }

  function resolvePromise (promiseReturn, x, resolve, reject) {
    // 判断then方法返回的Promise是否是自身的Promise对象
    if (promiseReturn === x) {
      return reject(new TypeError('Chaining cycle detected for promise #<Promise>'));
    }
    if (x instanceof MyPromise) {
      // Promise
      x.then(resolve, reject);
    } else {
      // 普通值
      resolve(x);
    }
  }

  /***********************************  end  ***********************************/


  /************************************ 测试 ***********************************/

  // const promise = new MyPromise((resolve, reject) => {
  //   setTimeout(() => {
  //     // resolve('成功......');
  //     // throw new Error('executor error')
  //     reject('失败......');
  //   }, 2000)
  //   // throw new Error('executor error')
  // })

  // function other () {
  //   return new MyPromise((resolve, reject) => {
  //     resolve('other')
  //   })
  // }

  // const p = promise.then(value => {
  //   console.log(value)
  // }, reason => {
  //   console.log('11', reason)

  // })


  function p1 () {
    return new MyPromise((resolve, reject) => {
      setTimeout(() => {
        resolve('p1')
      }, 2000)
    })
  }


  function p2 () {
    return new MyPromise((resolve, reject) => {
      resolve('p2')
    })
  }

  MyPromise.all(['a', 'b', p1(), p2(), "c"]).then(result => console.log(result))

  // MyPromise.resolve(10).then(value => console.log(value))

  const promise = new MyPromise((resolve, reject) => {
    // resolve('promise');
    reject('promise reject');
  })

  promise
    .then(value => p2())
    .then(value => console.log(value))
    .catch(reason => console.log(reason))
    .finally(() => console.log('finally'))
</script>

</html>